
theme: jekyll-theme-midnight
title: The Constitutions Project
description: Comparing and Contrasting the Constitutions of the World

menu : [
{'name': 'Home', 'pagename': 'index'},
{'name': 'Acknowledgements', 'pagename': 'page1'},
{'name': 'About the Project', 'pagename': 'AboutTheProject'},
{'name': 'Research', 'pagename': 'page3'},
{'name': 'Impact and Support', 'pagename': 'ImpactsandSupport'},
{'name': 'Regrouping Experiment', 'pagename': 'Regrouping'},
{'name': 'Case Study - Tunisia', 'pagename': 'page2'},
{'name': 'Resources', 'pagename': 'page4'},
]
