
theme: jekyll-theme-midnight
title: The Constitutions Project
description: Comparing and Contrasting the Constitutions of the World

menu : 
[{'name': 'Home', 'pagename': 'index'},
{'name': 'Acknowledgements', 'pagename': 'page1'}
{'name': 'About the Project', 'pagename': 'AboutTheProject'},
{'name': 'Methodology', 'pagename': 'page3'},
{'name': 'Case Study', 'pagename': 'page2'},
{'name': 'Resources', 'pagename': 'page4'},
]
