
theme: jekyll-theme-midnight
title: The Constitution Project
description: Comparing and Contrasting the Constitutions of the World
menu: [
{'name': 'Home', 'pagename': 'index'},
{'name': 'Constitutions', 'pagename': 'page1'},
{'name': 'Graphs', 'pagename': 'page2'},
{'name': 'Team members', 'pagename': 'page3'},
]
